amalieeh/assessment-support

components/textbox.tsx, pages/index.tsx
create #1 
Reusing the textbox-style from the example page.
The "textboxprop interface" is a bit wierd, but we will get to it... I hope
=> Add simple textbox

components/pointsbox.tsx, pages/assessment.tsx, styles/assessment.module.css
- create right and left arrow css
- add back and next functionality to the arrow
#15
=> 15 next arrow

components/expand.tsx, package-lock.json, package.json, pages/assessment.tsx, styles/assessment.module.css
- create a place for the task title and task description
- use accordion to create an expand component
#9
=> 9 task description

components/pointsbox.tsx, components/textbox.tsx, functions/helpFunctions.tsx, pages/assessment.tsx, pages/index.tsx, types/Types.tsx
Now the textbox gets data from the inspera dataset.
Also improvment on the som improvment on the cleanHtmlText() was done, although the function should probably be replaced later.
fix #22
=> Get answers from inspera dataset

pages/approval.tsx, pages/assessment.tsx
Now the assessment page ends in a button that leads to the new approval page.
In the approval page there is nothing except the possibility to go back :)
=> Add Approval page and link to/from it

components/header.tsx, pages/assessment.tsx, pages/index.tsx, styles/Header.module.css, styles/Home.module.css
Made a header component that is based on the dataset from Inspera and
optionally which task the user is assessing. Made `taskNumber` optional
so that the header component can be used on other pages than Assessment
Page as well.
The header should follow the width of the text boxes displaying answers.
=> Create header component #4

components/pointsbox.tsx
Not much to say.
We could perhaps change to MaterialUI dropdown since we use it other places? But it could be unnecessary work as well.
=> change placeholdertext in pointbox

functions/helpFunctions.tsx, types/Types.tsx
=> include candidate id in the datatype for textboxes. 

components/pointsbox.tsx, pages/task.tsx
- create set up for task page
- display task buttons
=> create task page and task buttons

components/header.tsx, pages/index.tsx, pages/task.tsx
And when clicking on task, you are lead to assessment page.
todo:
=> fix task page design and Link

pages/assessment.tsx, styles/assessment.module.css
added up and down arrows and kept right and left arrows in case we need them for later
#43
=> add up and down arrows

pages/approval.tsx, pages/assessment.tsx
Tasknumber is passed from assessment to approval making it possible to route back from approval to assessment. 
Fix #71
=> pass tasknumber from assessment to approval 

functions/helpFunctions.tsx, pages/assessment.tsx
created to functions for getting assessments to re-asses:
1. chooseFrequentAssessmentBasedOnScore. This always returns an outlier in the batch. Outliers can be amongst those that where the frequency is low or those where frequency is high. Passing b = true as a param in the function will give an outlier amongst those that have a high frequency(?). 
2. chooseCorrelatedAssessment. This is based on correlation of a high score and the length of answer, and will retrieve an answer or null
=> 60 re algorithm

components/expand.tsx, pages/assessment.tsx, styles/assessment.module.css
fix #39 
- Moved the task description and marker guidance info boxes tot he left side of the answer batch
- Changed from "marker guidance" to "sensorveiledning"
=> Reposition infoboxes

components/approvalTextbox.tsx, functions/helpFunctions.tsx, pages/approval.tsx
This is one step of #57
so #57 is not done, but tis is merged to main because of a demo for Trond :)
=> use real data on approval page

components/pointsbox.tsx, components/textbox.tsx, styles/Textbox.module.css
fix: #42 
- Resized pointsbox to be smaller
- Added candidate number to the answer
- Added scrolling of answer
=> 42 redesign textbox

components/approvalTextbox.tsx, pages/approval.tsx, types/Types.tsx
Now the components are ready to be used in a larger setting.
I chose to split some of these PRs up because there is a lot that should be changed a bit everywhere, so I'm trying to keep it nice and atomic 😅
=> Complete approval textboxes

package-lock.json, package.json, pages/assessment.tsx, styles/assessment.module.css
fix #83 
Created a togglebar which give the user options for choosing to have two, four or six student answers on display.
=> 83 select num of answers

pages/approval.tsx, pages/assessment.tsx, pages/index.tsx, pages/task.tsx
- fix togglebar to enforce that at least one button must be active
- change text on indexpage
- disable 3 task buttons
=> Fixes for demo

components/approvalTextbox.tsx, pages/approval.tsx, pages/assessment.tsx, types/Types.tsx
Now the approval texboxes work! 
(All though they still need functionality to change the scores of the students)
=> Fix approval page textbox logic

components/sortingbox.tsx, functions/sortAlgorithms.tsx, pages/assessment.tsx, styles/assessment.module.css
fix #81 
Created a drop down sorting box where the user can choose to sort the student answers byb:
- random
- candidate number
- length - high to low
- length - low to high
This currently works for the case when the data is loaded and no assessments have been made.
It later needs to be updated to only sort the rest of the assessments that have not been assessed.
This is in relation to data retrieval for textboxes.
=> 81 sort answers

components/sortingbox.tsx, components/togglebuttons.tsx, functions/sortAlgorithms.tsx, pages/assessment.tsx, styles/assessment.module.css
Moved togglebuttons to components for cleaner code.
This is branched out from #104
=> Quickfix: move togglebuttons

components/textbox.tsx, pages/approval.tsx, pages/assessment.tsx, styles/Textbox.module.css, types/Types.tsx
The user can flag answers. If reassessed, the flag follows and is the same as the oj assessment. It is not
used to anything particular as of now.
=> Add flagging option in assessments

functions/helpFunctions.tsx, pages/approval.tsx, pages/task.tsx
fix #7 fix #14 
When assessments are approved, they are saved to `localstorage` on key `{taskNumber_approved}`.
Task buttons are coloured based on the state of the assessments which are: approved (green), started (orange) and remaining (blue)
=> Approve assessments and update task buttons

components/approvalTextbox.tsx, components/pointsbox.tsx, components/textbox.tsx, package-lock.json, pages/approval.tsx, pages/assessment.tsx, yarn.lock
Fix #107 
You set scores on approval page. If you un-set a score on the approval page, the border turns red, indicating that a change is needed.
Also aligned the text with candidate number.
It only changes state, not the local storage, but I think that makes sorta sense, at least as of now.
But later, maybe it should be updated in local storage so that the user comes back to resolved "konflikter".
=> Set scores on approval page

components/header.tsx, pages/assessment.tsx, pages/task.tsx, styles/Header.module.css
fix #102 
Added a back to taskpage arrow in the header. Also changed the width of the header to 100%, and some small styling to make it fit with the arrow.
=> add back to taskpage arrow

functions/helpFunctions.tsx
=> remove unused return

functions/helpFunctions.tsx, pages/assessment.tsx
Fix comment in #115.  Now all answers are returned and the current page is set to where to user left off, and the user can go back and get all the previous scores assessments.
=> Fix get data

components/header.tsx, functions/helpFunctions.tsx, pages/approval.tsx, pages/assessment.tsx, pages/task.tsx
Fix a few minor issues i discovered after rebasing #118 
1. Removed saving of empty list to localStorage
2. Route to `approval page` when all assessments are assessed but not approved 
3. Fix the condition for approval page. It only checked for inconsistent scores at first but not empty scores
=> Fix routing

components/progressbar.tsx, pages/assessment.tsx
fix #82
It's a very basig progressbar. It works fine, but it is not very smart, so if we choose iffy numbers of consistency percentage the bar may underestimate how far the user has gotten.
It's super easy to change the size if you find it too small or something. :)
=> add basic progressbar

components/approvalTextbox.tsx, components/candidateTextbox.tsx, components/gradingbuttons.tsx, components/textbox.tsx, functions/helpFunctions.tsx, package.json, pages/approval.tsx, pages/candidate.tsx, pages/completion.tsx, pages/print.tsx, pages/task.tsx, styles/Completion.module.css, types/Types.tsx
Fix #63 #64 
A simple page is created viewing the grades of each student. The cards are clickable, and the page leads the "candidate page" which is where you can see all the answers and score (which is editable) to the student.
One check to get the tasks is commented out and the task numbers to be viewed are set manually so it is easier to test (aka you don't need to assess ALL of the tasks to view completion page with grades).
There is one warning in the console: Warning: Expected server HTML to contain a matching `<div>` in `<div>`.
A solutions is probably here: https://localcoder.org/react-16-warning-expected-server-html-to-contain-a-matching-div-in-body, but it took me some time trying to understand so I'll rather prioritise other development.
=> Create completion page
